"""add documents and documentlines

Revision ID: ec87a3d9576d
Revises: 26469f083a23
Create Date: 2025-09-28 19:52:09.750592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec87a3d9576d'
down_revision = '26469f083a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=3), nullable=False),
    sa.Column('total_quantity', sa.Float(), nullable=False),
    sa.Column('received_by', sa.String(length=100), nullable=False),
    sa.Column('delivered_by', sa.String(length=100), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_document_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_lines')
    op.drop_table('documents')
    # ### end Alembic commands ###
